In [1]:
import numpy as np #np is an alias of numpy

In [2]:
my_list=[1,2,3,4,5]

In [3]:
print(my_list)

[1, 2, 3, 4, 5]


In [4]:
type(my_list)

list

In [5]:
#converting list into array
arr=np.array(my_list) # n=1 i.e 1 dimentional array

In [6]:
print(arr)

[1 2 3 4 5]


In [7]:
type(arr)

numpy.ndarray

In [9]:
#multinested array
my_list=[1,2,3,4,5]
my_list_2=[2,3,5,6,7]
my_list_3=[3,7,1,8,9]

arr_new=np.array([my_list,my_list_2,my_list_3]) # n=2 i.e. 2 dimentional array

In [10]:
print(arr_new)

[[1 2 3 4 5]
 [2 3 5 6 7]
 [3 7 1 8 9]]


In [11]:
arr_new.shape # 3 is the number of rows and 5 is the number of columns

(3, 5)

In [12]:
arr_new.reshape(5,3)

array([[1, 2, 3],
       [4, 5, 2],
       [3, 5, 6],
       [7, 3, 7],
       [1, 8, 9]])

In [13]:
arr_new.reshape(5,4)

ValueError: ignored

In [14]:
#indexing and slicing in Numpy 

In [15]:
print(arr)

[1 2 3 4 5]


In [16]:
arr[3]

4

In [17]:
arr[1:4]

array([2, 3, 4])

In [18]:
arr[:3]

array([1, 2, 3])

In [19]:
arr[2:]

array([3, 4, 5])

In [20]:
print(arr_new)

[[1 2 3 4 5]
 [2 3 5 6 7]
 [3 7 1 8 9]]


In [23]:
arr_new[0:2,0:2]

array([[1, 2],
       [2, 3]])

In [24]:
arr_new[1:,1:]

array([[3, 5, 6, 7],
       [7, 1, 8, 9]])

In [21]:
arr_new[1:,3:] 

array([[6, 7],
       [8, 9]])

In [22]:
arr_new[0:,1:3] 

array([[2, 3],
       [3, 5],
       [7, 1]])

In [25]:
#generating random numbers through NUMPY

In [26]:
arr=np.arange(0,10,step=1) # 10 is exclusive and we get elements from 0--9 which are equally spaced 

In [27]:
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [28]:
arr=np.arange(1,15,step=2)

In [29]:
print(arr)

[ 1  3  5  7  9 11 13]


In [33]:
np.linspace(1,10,50) # 1-->9 we get 50 elements which are equally spaced

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [40]:
np.random.rand(3,4) #3 stands for 3 rows and 4 stands for 4 columns 
#incase of random.rand the range is 0-->1 by default 
#the random elements  that we get are floating point numbers

array([[0.89110082, 0.05234895, 0.09510281, 0.59709436],
       [0.52913378, 0.32735964, 0.84666704, 0.00829116],
       [0.84178897, 0.63515251, 0.41023308, 0.97752251]])

In [47]:
np.random.randint(5,20,5) # 5-->20 is the range specified 
#and the number of elements in this range is 5
#the random elements  that we get are integer numbers

array([13, 12, 17, 17, 10])